detect_ball:
  ros__parameters:
    tuning_model: true
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100
    h_min: 30
    h_max: 37
    s_min: 42
    v_min: 0
    v_max: 255
    sz_min: 0
    sz_max: 100


